# Generated by Django 2.0.2 on 2018-02-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_song_is_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='is_favourite',
            new_name='is_favorite',
        ),
    ]
